version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/robyndb
      - ENVIRONMENT=development
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - robyn-network

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=robyndb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - robyn-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db
    networks:
      - robyn-network

volumes:
  postgres_data:

networks:
  robyn-network:
    driver: bridge 